import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import {  FaPenSquare, FaLinkedin, FaMedium } from 'react-icons/fa'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark":""}>
      <Head>
        <title>Bayu Angkus Prana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-bayudark'>
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-fontdark'>BAP</h1>
            <ul className='flex items-center'>
              <li><a href='https://medium.com/@bungkusprana' target="_blank" rel='nonereferrer' className='font-poppins m-8 dark:text-fontdark'>Medium</a></li>
              <li><a href='#' className='font-poppins m-8 dark:text-fontdark' rel='nonereferrer'>Blog</a></li>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl ml-8  dark:text-fontdark' onClick={() => setDarkMode(!darkMode)} /></li>
              <li><a className='bg-bayu text-white px-4 py-2 rounded-md ml-8 font-poppins drop-shadow-lg dark:drop-shadow-lg' href='https://www.linkedin.com/in/bungkusprana/?originalSubdomain=id' target="_blank">Resume</a></li>
            </ul>
          </nav>

          <div className='text-center pt-10'>
            <h2 className='text-5xl py-2 text-bayu font-semibold md:text-6xl dark:drop-shadow-lg'>Bayu Angkus Prana</h2>
            <h3 className='text-2xl py-2 font-lg md:text-3xl dark:text-fontdark'>Copywriter</h3>
            <p className='text-md py-10 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white'>Cupcake ipsum dolor sit amet danish bonbon dragée gummi.Shortbread gingerbread tiramisu sugar plum biscuit chocolate.</p>
          </div>

          <div className='text-4xl flex justify-center gap-16 py-5 text-gray-600'>
            <a href='https://medium.com/@bungkusprana' target="_blank" rel='nonereferrer' className='dark:text-gray-300'><FaMedium /></a>
            <a href='https://www.linkedin.com/in/bungkusprana/?originalSubdomain=id' rel='nonereferrer' target="_blank" className='dark:text-gray-300'><FaLinkedin /></a>
            <a href='#' target="_blank" className='dark:text-gray-300'><FaPenSquare /></a>
            
          </div>

          <div className='relative mx-auto bg-gradient-to-b from-bayu rounded-full w-80 h-80 mt-[50px] overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout="fill" objectFit='cover' />
          </div>
        </section>

        {/* <section className='pt-20'>
          <div>
            <h3 className='text-3xl py-1'>Cupcake Ipsum</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
              Cupcake ipsum dolor sit amet danish bonbon dragée gummi.<br />Shortbread gingerbread tiramisu sugar plum biscuit chocolate.
            </p>
          </div>
        <div>

        <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <Image src={design} width={100} height={100}/>
            <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
            <p className='py-2 '>Cupcake ipsum dolor sit amet danish bonbon dragée gummi.</p>
            <h4 className='py-4 text-bayu'>Design tools I use</h4>
            <p className='text-gray-800 py-1'>Photoshop</p>
            <p className='text-gray-800 py-1'>Adobe Illustrator</p>
            <p className='text-gray-800 py-1'>Canva</p>
          </div>

          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <Image src={writer} width={100} height={100}/>
            <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
            <p className='py-2 '>Cupcake ipsum dolor sit amet danish bonbon dragée gummi.</p>
            <h4 className='py-4 text-bayu'>Design tools I use</h4>
            <p className='text-gray-800 py-1'>Photoshop</p>
            <p className='text-gray-800 py-1'>Adobe Illustrator</p>
            <p className='text-gray-800 py-1'>Canva</p>
          </div>

          <div className='text-center shadow-lg p-10 rounded-xl my-10'>
            <Image src={cons} width={100} height={100}/>
            <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
            <p className='py-2 '>Cupcake ipsum dolor sit amet danish bonbon dragée gummi.</p>
            <h4 className='py-4 text-bayu'>Design tools I use</h4>
            <p className='text-gray-800 py-1'>Photoshop</p>
            <p className='text-gray-800 py-1'>Adobe Illustrator</p>
            <p className='text-gray-800 py-1'>Canva</p>
          </div>
        </div>
        </section>

        <section>
          <div>
          <h3 className='text-3xl py-1'>Cupcake Ipsum</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
              Cupcake ipsum dolor sit amet danish bonbon dragée gummi.<br />Shortbread gingerbread tiramisu sugar plum biscuit chocolate.
            </p>
          </div>

        </section> */}
      </main>
    </div>
  );
}
